#!/bin/sh

echo "Please enter your password:"
read password
length=`echo "$password" | wc -c`
length=`expr $length - 1`
if [ $length -lt 8 ]; then
  echo "Password must be at least 8 characters long."
else
  uppercase=`echo "$password" | grep '[A-Z]'`
  if [ -z "$uppercase" ]; then
    echo "Password must contain at least one uppercase letter."
  else
    digit=`echo "$password" | grep '[0-9]'`
    if [ -z "$digit" ]; then
      echo "Password must contain at least one digit."
    else
      echo "Password is valid."
    fi
  fi
fi
