#!/bin/sh

school_url="http://www.schoolwebsite.edu"
while true
do
  wget -q --spider "$school_url"
  if [ $? -eq 0 ]; then
    echo "Internet connection to the school's website is available."
    echo "Opening the school homepage in Firefox..."
    firefox "$school_url"
    break
  else
    echo "Warning: No connection to the school's website. Retrying in 5 seconds..."
    sleep 5
  fi
done
